# Generated by Django 4.2 on 2024-07-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dentista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('formacion', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='dentistas_fotos/')),
            ],
        ),
    ]
