# Generated by Django 4.2 on 2024-07-23 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentistas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentista',
            name='foto',
        ),
    ]
