# Generated by Django 4.2 on 2024-07-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='disponible',
            field=models.BooleanField(default=False),
        ),
    ]
